version: '3.3'

services:
  ihold_front_web_nginx:
    container_name: ihold_front_web_nginx
    build:
      context: .
      dockerfile: docker/config/nginx/production.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.ihold_front_web_nginx.rule=Host(`internetbanking.iholdbank.digitall`)"
      - "traefik.http.routers.ihold_front_web_nginx.entrypoints=websecure"
      - "traefik.http.routers.ihold_front_web_nginx.tls=true"
      - "traefik.http.routers.ihold_front_web_nginx.tls.certresolver=iholdresolver"
    networks:
      - internal
      - web

  ihold_front_web:
    container_name: ihold_front_web
    build:
      context: .
      dockerfile: docker/config/app/app.Dockerfile
    networks:
      - internal

networks:
  web:
    external: true

  internal:
    external: false